# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/
name: Fly Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Instalar flyctl
      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      # Autenticarse con el deploy token
      - name: Authenticate Fly
        run: flyctl auth token ${{ secrets.FLY_API_TOKEN }}

      # Hacer deploy de la app
      - name: Deploy to Fly
        run: flyctl deploy --remote-only

